name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore Dependencies
      run: dotnet restore src
    - name: Build
      run: dotnet build src --configuration Release --no-restore
    - name: Unit Test
      run: |
        cd ./tests/Markdig.ColorCode.UnitTests/
        dotnet test --no-restore /p:CollectCoverage=true /p:CoverletOutput=/home/runner/work/markdig-colorcode/markdig-colorcode/ /p:CoverletOutputFormat=opencover
    - name: Publish Code Coverage
      uses: codecov/codecov-action@v2
      with:
        files: /home/runner/work/markdig-colorcode/markdig-colorcode/coverage.opencover.xml
        fail_ci_if_error: true
