name: Build and Deploy Documentation

on:
  push:
    branches: [ documentation_tweaks ]

jobs:
  deploy-docs:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Build Docs
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: docs/docfx.json

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@4.2.0
        with:
          branch: gh-pages
          folder: site/html
          git-config-email: <>
